// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AcceptLoanOfferInput struct {
	OfferID string `json:"offerId"`
}

type AuthResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type CreateLoanOfferInput struct {
	Amount             float64            `json:"amount"`
	InterestRate       float64            `json:"interestRate"`
	Term               int32              `json:"term"`
	ExpiresAt          time.Time          `json:"expiresAt"`
	RepaymentFrequency RepaymentFrequency `json:"repaymentFrequency"`
}

type CreateLoanRequestInput struct {
	Amount             float64            `json:"amount"`
	Purpose            *string            `json:"purpose,omitempty"`
	Term               int32              `json:"term"`
	MaxInterestRate    *float64           `json:"maxInterestRate,omitempty"`
	RepaymentFrequency RepaymentFrequency `json:"repaymentFrequency"`
}

type Installment struct {
	DueDate   time.Time     `json:"dueDate"`
	Amount    float64       `json:"amount"`
	Principal float64       `json:"principal"`
	Interest  float64       `json:"interest"`
	Status    PaymentStatus `json:"status"`
	PaidAt    *time.Time    `json:"paidAt,omitempty"`
	CreatedAt time.Time     `json:"createdAt"`
	UpdatedAt time.Time     `json:"updatedAt"`
}

type Loan struct {
	ID                 string             `json:"id"`
	Borrower           *User              `json:"borrower"`
	Lender             *User              `json:"lender"`
	Amount             float64            `json:"amount"`
	InterestRate       float64            `json:"interestRate"`
	Term               int32              `json:"term"`
	Status             LoanStatus         `json:"status"`
	Payments           []*Payment         `json:"payments"`
	NextPaymentDue     *time.Time         `json:"nextPaymentDue,omitempty"`
	RemainingBalance   float64            `json:"remainingBalance"`
	RepaymentFrequency RepaymentFrequency `json:"repaymentFrequency"`
	Installments       []*Installment     `json:"installments"`
	TotalInterest      float64            `json:"totalInterest"`
	TotalRepayment     float64            `json:"totalRepayment"`
	CreatedAt          time.Time          `json:"createdAt"`
	UpdatedAt          time.Time          `json:"updatedAt"`
}

type LoanMatch struct {
	Request *LoanRequest `json:"request"`
	Offers  []*LoanOffer `json:"offers"`
}

type LoanOffer struct {
	ID                 string             `json:"id"`
	Lender             *User              `json:"lender"`
	Amount             float64            `json:"amount"`
	InterestRate       float64            `json:"interestRate"`
	Term               int32              `json:"term"`
	RepaymentFrequency RepaymentFrequency `json:"repaymentFrequency"`
	Status             OfferStatus        `json:"status"`
	ExpiresAt          time.Time          `json:"expiresAt"`
	CreatedAt          time.Time          `json:"createdAt"`
	UpdatedAt          time.Time          `json:"updatedAt"`
}

type LoanRequest struct {
	ID                 string             `json:"id"`
	User               *User              `json:"user"`
	Amount             float64            `json:"amount"`
	Purpose            *string            `json:"purpose,omitempty"`
	Status             LoanStatus         `json:"status"`
	Term               int32              `json:"term"`
	InterestRate       *float64           `json:"interestRate,omitempty"`
	RepaymentFrequency RepaymentFrequency `json:"repaymentFrequency"`
	CreatedAt          time.Time          `json:"createdAt"`
	UpdatedAt          time.Time          `json:"updatedAt"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type MakePaymentInput struct {
	LoanID string  `json:"loanId"`
	Amount float64 `json:"amount"`
}

type Mutation struct {
}

type Payment struct {
	ID          string        `json:"id"`
	Loan        *Loan         `json:"loan"`
	Amount      float64       `json:"amount"`
	DueDate     time.Time     `json:"dueDate"`
	Status      PaymentStatus `json:"status"`
	PaidAt      *time.Time    `json:"paidAt,omitempty"`
	Installment *Installment  `json:"installment,omitempty"`
	CreatedAt   time.Time     `json:"createdAt"`
	UpdatedAt   time.Time     `json:"updatedAt"`
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type Subscription struct {
}

type User struct {
	ID          string    `json:"id"`
	Email       string    `json:"email"`
	Name        string    `json:"name"`
	CreditScore *int32    `json:"creditScore,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type LoanStatus string

const (
	LoanStatusPending   LoanStatus = "PENDING"
	LoanStatusActive    LoanStatus = "ACTIVE"
	LoanStatusCompleted LoanStatus = "COMPLETED"
	LoanStatusDefaulted LoanStatus = "DEFAULTED"
	LoanStatusCancelled LoanStatus = "CANCELLED"
)

var AllLoanStatus = []LoanStatus{
	LoanStatusPending,
	LoanStatusActive,
	LoanStatusCompleted,
	LoanStatusDefaulted,
	LoanStatusCancelled,
}

func (e LoanStatus) IsValid() bool {
	switch e {
	case LoanStatusPending, LoanStatusActive, LoanStatusCompleted, LoanStatusDefaulted, LoanStatusCancelled:
		return true
	}
	return false
}

func (e LoanStatus) String() string {
	return string(e)
}

func (e *LoanStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LoanStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LoanStatus", str)
	}
	return nil
}

func (e LoanStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LoanStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LoanStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OfferStatus string

const (
	OfferStatusOpen      OfferStatus = "OPEN"
	OfferStatusAccepted  OfferStatus = "ACCEPTED"
	OfferStatusRejected  OfferStatus = "REJECTED"
	OfferStatusExpired   OfferStatus = "EXPIRED"
	OfferStatusWithdrawn OfferStatus = "WITHDRAWN"
)

var AllOfferStatus = []OfferStatus{
	OfferStatusOpen,
	OfferStatusAccepted,
	OfferStatusRejected,
	OfferStatusExpired,
	OfferStatusWithdrawn,
}

func (e OfferStatus) IsValid() bool {
	switch e {
	case OfferStatusOpen, OfferStatusAccepted, OfferStatusRejected, OfferStatusExpired, OfferStatusWithdrawn:
		return true
	}
	return false
}

func (e OfferStatus) String() string {
	return string(e)
}

func (e *OfferStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OfferStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OfferStatus", str)
	}
	return nil
}

func (e OfferStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OfferStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OfferStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PaymentStatus string

const (
	PaymentStatusPending       PaymentStatus = "PENDING"
	PaymentStatusPaid          PaymentStatus = "PAID"
	PaymentStatusLate          PaymentStatus = "LATE"
	PaymentStatusPartiallyPaid PaymentStatus = "PARTIALLY_PAID"
	PaymentStatusCancelled     PaymentStatus = "CANCELLED"
)

var AllPaymentStatus = []PaymentStatus{
	PaymentStatusPending,
	PaymentStatusPaid,
	PaymentStatusLate,
	PaymentStatusPartiallyPaid,
	PaymentStatusCancelled,
}

func (e PaymentStatus) IsValid() bool {
	switch e {
	case PaymentStatusPending, PaymentStatusPaid, PaymentStatusLate, PaymentStatusPartiallyPaid, PaymentStatusCancelled:
		return true
	}
	return false
}

func (e PaymentStatus) String() string {
	return string(e)
}

func (e *PaymentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaymentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaymentStatus", str)
	}
	return nil
}

func (e PaymentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PaymentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PaymentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RepaymentFrequency string

const (
	RepaymentFrequencyDaily     RepaymentFrequency = "DAILY"
	RepaymentFrequencyWeekly    RepaymentFrequency = "WEEKLY"
	RepaymentFrequencyBiweekly  RepaymentFrequency = "BIWEEKLY"
	RepaymentFrequencyMonthly   RepaymentFrequency = "MONTHLY"
	RepaymentFrequencyQuarterly RepaymentFrequency = "QUARTERLY"
	RepaymentFrequencyYearly    RepaymentFrequency = "YEARLY"
)

var AllRepaymentFrequency = []RepaymentFrequency{
	RepaymentFrequencyDaily,
	RepaymentFrequencyWeekly,
	RepaymentFrequencyBiweekly,
	RepaymentFrequencyMonthly,
	RepaymentFrequencyQuarterly,
	RepaymentFrequencyYearly,
}

func (e RepaymentFrequency) IsValid() bool {
	switch e {
	case RepaymentFrequencyDaily, RepaymentFrequencyWeekly, RepaymentFrequencyBiweekly, RepaymentFrequencyMonthly, RepaymentFrequencyQuarterly, RepaymentFrequencyYearly:
		return true
	}
	return false
}

func (e RepaymentFrequency) String() string {
	return string(e)
}

func (e *RepaymentFrequency) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RepaymentFrequency(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RepaymentFrequency", str)
	}
	return nil
}

func (e RepaymentFrequency) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RepaymentFrequency) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RepaymentFrequency) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
