package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/dmytroMai20/Daneo/graph/model"
	"github.com/dmytroMai20/Daneo/models"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthResponse, error) {
	panic(fmt.Errorf("not implemented: Register - register"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthResponse, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// CreateLoanRequest is the resolver for the createLoanRequest field.
func (r *mutationResolver) CreateLoanRequest(ctx context.Context, input model.CreateLoanRequestInput) (*model.LoanRequest, error) {
	pool, ok := ctx.Value(models.DBContextKey).(*pgxpool.Pool)
	if !ok || pool == nil {
		return nil, fmt.Errorf("database connection not available")
	}

	// Get user ID from context (assuming it's set by auth middleware)
	//userID, ok := ctx.Value("userID").(string)
	//if !ok {
	//	return nil, fmt.Errorf("user not authenticated")
	//}
	userID := "1"

	tx, err := pool.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %v", err)
	}
	defer tx.Rollback(ctx)

	var loanRequest model.LoanRequest
	err = tx.QueryRow(ctx, `
		INSERT INTO loan_requests (user_id, amount, purpose, term, interest_rate, status)
		VALUES ($1, $2, $3, $4, $5, 'PENDING')
		RETURNING id, created_at, updated_at
	`, userID, input.Amount, input.Purpose, input.Term, input.MaxInterestRate).
		Scan(&loanRequest.ID, &loanRequest.CreatedAt, &loanRequest.UpdatedAt)

	if err != nil {
		return nil, fmt.Errorf("failed to create loan request: %v", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %v", err)
	}

	loanRequest.Amount = input.Amount
	loanRequest.Purpose = input.Purpose
	loanRequest.Term = input.Term
	loanRequest.InterestRate = input.MaxInterestRate
	loanRequest.Status = model.LoanStatusPending

	loanRequest.User = &model.User{
		ID: userID,
		// Other user fields would be populated from the database
	}

	return &loanRequest, nil
}

// CancelLoanRequest is the resolver for the cancelLoanRequest field.
func (r *mutationResolver) CancelLoanRequest(ctx context.Context, requestID string) (bool, error) {
	panic(fmt.Errorf("not implemented: CancelLoanRequest - cancelLoanRequest"))
}

// CreateLoanOffer is the resolver for the createLoanOffer field.
func (r *mutationResolver) CreateLoanOffer(ctx context.Context, input model.CreateLoanOfferInput) (*model.LoanOffer, error) {
	panic(fmt.Errorf("not implemented: CreateLoanOffer - createLoanOffer"))
}

// CancelLoanOffer is the resolver for the cancelLoanOffer field.
func (r *mutationResolver) CancelLoanOffer(ctx context.Context, offerID string) (bool, error) {
	panic(fmt.Errorf("not implemented: CancelLoanOffer - cancelLoanOffer"))
}

// AcceptLoanOffer is the resolver for the acceptLoanOffer field.
func (r *mutationResolver) AcceptLoanOffer(ctx context.Context, input model.AcceptLoanOfferInput) (*model.Loan, error) {
	panic(fmt.Errorf("not implemented: AcceptLoanOffer - acceptLoanOffer"))
}

// MakePayment is the resolver for the makePayment field.
func (r *mutationResolver) MakePayment(ctx context.Context, input model.MakePaymentInput) (*model.Payment, error) {
	panic(fmt.Errorf("not implemented: MakePayment - makePayment"))
}

// UpdateUserStatus is the resolver for the updateUserStatus field.
func (r *mutationResolver) UpdateUserStatus(ctx context.Context, userID string, active bool) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UpdateUserStatus - updateUserStatus"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// MyLoanRequests is the resolver for the myLoanRequests field.
func (r *queryResolver) MyLoanRequests(ctx context.Context) ([]*model.LoanRequest, error) {
	panic(fmt.Errorf("not implemented: MyLoanRequests - myLoanRequests"))
}

// MyLoanOffers is the resolver for the myLoanOffers field.
func (r *queryResolver) MyLoanOffers(ctx context.Context) ([]*model.LoanOffer, error) {
	panic(fmt.Errorf("not implemented: MyLoanOffers - myLoanOffers"))
}

// MyActiveLoans is the resolver for the myActiveLoans field.
func (r *queryResolver) MyActiveLoans(ctx context.Context) ([]*model.Loan, error) {
	panic(fmt.Errorf("not implemented: MyActiveLoans - myActiveLoans"))
}

// AvailableLoanRequests is the resolver for the availableLoanRequests field.
func (r *queryResolver) AvailableLoanRequests(ctx context.Context) ([]*model.LoanRequest, error) {
	panic(fmt.Errorf("not implemented: AvailableLoanRequests - availableLoanRequests"))
}

// AvailableLoanOffers is the resolver for the availableLoanOffers field.
func (r *queryResolver) AvailableLoanOffers(ctx context.Context) ([]*model.LoanOffer, error) {
	panic(fmt.Errorf("not implemented: AvailableLoanOffers - availableLoanOffers"))
}

// AllLoans is the resolver for the allLoans field.
func (r *queryResolver) AllLoans(ctx context.Context) ([]*model.Loan, error) {
	panic(fmt.Errorf("not implemented: AllLoans - allLoans"))
}

// AllUsers is the resolver for the allUsers field.
func (r *queryResolver) AllUsers(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: AllUsers - allUsers"))
}

// LoanRequestCreated is the resolver for the loanRequestCreated field.
func (r *subscriptionResolver) LoanRequestCreated(ctx context.Context) (<-chan *model.LoanRequest, error) {
	panic(fmt.Errorf("not implemented: LoanRequestCreated - loanRequestCreated"))
}

// LoanOfferCreated is the resolver for the loanOfferCreated field.
func (r *subscriptionResolver) LoanOfferCreated(ctx context.Context) (<-chan *model.LoanOffer, error) {
	panic(fmt.Errorf("not implemented: LoanOfferCreated - loanOfferCreated"))
}

// LoanStatusChanged is the resolver for the loanStatusChanged field.
func (r *subscriptionResolver) LoanStatusChanged(ctx context.Context, loanID string) (<-chan *model.Loan, error) {
	panic(fmt.Errorf("not implemented: LoanStatusChanged - loanStatusChanged"))
}

// PaymentReceived is the resolver for the paymentReceived field.
func (r *subscriptionResolver) PaymentReceived(ctx context.Context, loanID string) (<-chan *model.Payment, error) {
	panic(fmt.Errorf("not implemented: PaymentReceived - paymentReceived"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
